version: '3.3'

services:
  mysql:
      image: mysql:5
      environment:
          - MYSQL_DATABASE=TeamSupport
          - MYSQL_USER=jj
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_PORT=3306
      ports:
          - "3306:3306"
      volumes:
          - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=admin11
      - PMA_HOST=mysql
    ports:
      - 8080:80
